### ISSUE TITLE
Nothing happens with Work Sans

### ISSUE THREAD

**Issue by hyphone** [rafaelmardojai/webfont-kit-generator#23]
Hello and good day,

usually I don't have many problems with the applications but some happen from time to time.

For example when I download this font family and I select all files with Webfont Kit Generator and try to convert them the progress stays at 0% and this happens:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/webfontkitgenerator/webfontkitgenerator/generator.py", line 51, in generate
    self._generate_font(font.path, font.data)
  File "/app/share/webfontkitgenerator/webfontkitgenerator/generator.py", line 73, in _generate_font
    subs.subset(font)
  File "/app/lib/python3.8/site-packages/fontTools/subset/__init__.py", line 2704, in subset
    self._prune_post_subset(font)
  File "/app/lib/python3.8/site-packages/fontTools/subset/__init__.py", line 2687, in _prune_post_subset
    retain = table.prune_post_subset(font, self.options)
  File "/app/lib/python3.8/site-packages/fontTools/subset/__init__.py", line 1638, in prune_post_subset
    if not (table.FeatureList and table.FeatureVariations.FeatureVariationRecord):
AttributeError: 'NoneType' object has no attribute 'FeatureVariationRecord'
```

**Comment by rafaelmardojai** [comment]
Thanks for reporting, I will check this soon.

**Comment by rafaelmardojai** [comment]
Seems to be an issue with fonttools, the library used by this app. Updating fonttools should do the trick, I will update the flatpak these days.

**Comment by rafaelmardojai** [comment]
New version on flathub should work just fine.
