### ISSUE TITLE
Unmet dependencies with meson build on Debian Trixie

### ISSUE THREAD

**Issue by phpony** [rafaelmardojai/webfont-kit-generator#40]
Successfully builds but doesn't work out-of-a-box with meson build, needs 2 additional system packages:

```
apt-get install gir1.2-gtksource-5 fonttools
```

Probably worth a mention in Build section of readme, or should be checked during install.

Without them raises exceptions:

```
Traceback (most recent call last):
  File "/usr/local/bin/webfontkitgenerator", line 48, in <module>
    from webfontkitgenerator import main
  File "/usr/local/share/webfontkitgenerator/webfontkitgenerator/main.py", line 13, in <module>
    gi.require_version('GtkSource', '5')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace GtkSource not available for version 5
```

```
Traceback (most recent call last):
  File "/usr/local/bin/webfontkitgenerator", line 48, in <module>
    from webfontkitgenerator import main
  File "/usr/local/share/webfontkitgenerator/webfontkitgenerator/main.py", line 19, in <module>
    from webfontkitgenerator.window import Window
  File "/usr/local/share/webfontkitgenerator/webfontkitgenerator/window.py", line 10, in <module>
    from webfontkitgenerator.generator import Generator
  File "/usr/local/share/webfontkitgenerator/webfontkitgenerator/generator.py", line 9, in <module>
    from fontTools.subset import Subsetter, parse_unicodes
ModuleNotFoundError: No module named 'fontTools'
```

**Comment by rafaelmardojai** [comment]
True, I'm missing to check GtkSource in meson.

Sadly to my knowledge there's no way to check a python dep in meson, but will add it in the README.
